apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b1btp2jeo-go 
  janus-idp.io/tekton: b1btp2jeo-go
  backstage.io/kubernetes-id: b1btp2jeo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b1btp2jeo-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml